plugins {
  id 'application'
}

repositories {
  mavenCentral()
  gradlePluginPortal()
}

ext {
  gdxVersion = '1.12.1'
}

application {
  mainClass = 'si.um.feri.Gutic.lwjgl3.Lwjgl3Launcher'
}

dependencies {
  implementation project(':core')
  implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
  implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
  implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

sourceSets {
  main {
    resources {
      srcDirs = ["../assets"]
    }
  }
}

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

run {
  workingDir = rootProject.file('assets').path
  if (System.properties['os.name'].toLowerCase().contains('mac')) {
    jvmArgs += "-XstartOnFirstThread"
  }
}

jar {
  archiveFileName.set("${project.name}.jar")
  duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
  from {
    configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
  }
  manifest {
    attributes 'Main-Class': application.mainClass
  }
}
